# Generated by Django 5.1.6 on 2025-03-04 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_meal_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='side',
            field=models.CharField(choices=[('fries', 'Fries'), ('chips', 'Chips'), ('fruit', 'Fruit')], default='fries', max_length=10),
        ),
    ]
