# Generated by Django 5.1.6 on 2025-03-04 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_meal_side'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='category',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('entree', 'Entree'), ('appetizer', 'Appetizer'), ('dessert', 'Dessert'), ('beverage', 'Beverage'), ('side', 'Side'), ('other', 'Other')], default='entree', max_length=10),
        ),
    ]
