# Generated by Django 5.1.6 on 2025-03-04 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_meal_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='mealSwipe',
            field=models.BooleanField(default=False),
        ),
    ]
