# Generated by Django 5.1.6 on 2025-03-09 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_meal_mealswipe'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='category',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('entree', 'Entree'), ('appetizer', 'Appetizer'), ('dessert', 'Dessert'), ('beverage', 'Beverage'), ('side', 'Side'), ('other', 'Other')], default='entree', max_length=50),
        ),
        migrations.AlterField(
            model_name='meal',
            name='side',
            field=models.CharField(choices=[('fries', 'Fries'), ('sweet_potato_fries', 'Sweet Potato Fries'), ('chips', 'Chips'), ('fruit', 'Fruit')], default='fries', max_length=50),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('preparing', 'Preparing'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price_at_order', models.DecimalField(decimal_places=2, max_digits=6)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.meal')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
        ),
    ]
