# Generated by Django 5.1.6 on 2025-03-30 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_meal_category_alter_meal_side_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
